manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/DoctorWangWang
  projects:
    - name: 64key-3610
      remote: zmkfirmware
      revision: 64key-3610-automouse
      import: app/west.yml
  self:
    path: config
